/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void PURPLE_SCHEME(GButton source, GEvent event) { //_CODE_:button1:793369:
  technobeat();
} //_CODE_:button1:793369:

public void btn2(GButton source, GEvent event) { //_CODE_:button2:868503:
  percussion();
} //_CODE_:button2:868503:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:610892:
  greek();
} //_CODE_:button3:610892:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:893494:
  acid();
} //_CODE_:button4:893494:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:636851:
  drumbeats();
} //_CODE_:button5:636851:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:677183:
  cokeloop();
} //_CODE_:button6:677183:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.GOLD_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 30, 20, 60, 60);
  button1.setText("try me");
  button1.setTextBold();
  button1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  button1.addEventHandler(this, "PURPLE_SCHEME");
  button2 = new GButton(this, 250, 20, 60, 60);
  button2.setText("i dare you");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "btn2");
  button3 = new GButton(this, 130, 20, 80, 60);
  button3.setText("experiment");
  button3.setLocalColorScheme(GCScheme.RED_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 350, 20, 80, 60);
  button4.setText("don't be scared");
  button4.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 470, 20, 80, 60);
  button5.setText("good");
  button5.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 590, 20, 90, 60);
  button6.setText("i told you it'll be good");
  button6.addEventHandler(this, "button6_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
